/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedSenderIndexRouteImport } from './routes/_authenticated/sender/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSenderComposeRouteImport } from './routes/_authenticated/sender/compose'
import { Route as AuthenticatedAdminSmtpRouteImport } from './routes/_authenticated/admin/smtp'
import { Route as AuthenticatedAdminSendersRouteImport } from './routes/_authenticated/admin/senders'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminCsvRouteImport } from './routes/_authenticated/admin/csv'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSenderIndexRoute =
  AuthenticatedSenderIndexRouteImport.update({
    id: '/sender/',
    path: '/sender/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSenderComposeRoute =
  AuthenticatedSenderComposeRouteImport.update({
    id: '/sender/compose',
    path: '/sender/compose',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSmtpRoute = AuthenticatedAdminSmtpRouteImport.update({
  id: '/admin/smtp',
  path: '/admin/smtp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSendersRoute =
  AuthenticatedAdminSendersRouteImport.update({
    id: '/admin/senders',
    path: '/admin/senders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminCsvRoute = AuthenticatedAdminCsvRouteImport.update({
  id: '/admin/csv',
  path: '/admin/csv',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/admin/csv': typeof AuthenticatedAdminCsvRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/senders': typeof AuthenticatedAdminSendersRoute
  '/admin/smtp': typeof AuthenticatedAdminSmtpRoute
  '/sender/compose': typeof AuthenticatedSenderComposeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/sender/': typeof AuthenticatedSenderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/admin/csv': typeof AuthenticatedAdminCsvRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/senders': typeof AuthenticatedAdminSendersRoute
  '/admin/smtp': typeof AuthenticatedAdminSmtpRoute
  '/sender/compose': typeof AuthenticatedSenderComposeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/sender': typeof AuthenticatedSenderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/admin/csv': typeof AuthenticatedAdminCsvRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/senders': typeof AuthenticatedAdminSendersRoute
  '/_authenticated/admin/smtp': typeof AuthenticatedAdminSmtpRoute
  '/_authenticated/sender/compose': typeof AuthenticatedSenderComposeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/sender/': typeof AuthenticatedSenderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/super-admin'
    | '/admin/csv'
    | '/admin/logs'
    | '/admin/senders'
    | '/admin/smtp'
    | '/sender/compose'
    | '/admin/'
    | '/sender/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/super-admin'
    | '/admin/csv'
    | '/admin/logs'
    | '/admin/senders'
    | '/admin/smtp'
    | '/sender/compose'
    | '/admin'
    | '/sender'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/_authenticated/super-admin'
    | '/_authenticated/admin/csv'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/senders'
    | '/_authenticated/admin/smtp'
    | '/_authenticated/sender/compose'
    | '/_authenticated/admin/'
    | '/_authenticated/sender/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sender/': {
      id: '/_authenticated/sender/'
      path: '/sender'
      fullPath: '/sender/'
      preLoaderRoute: typeof AuthenticatedSenderIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sender/compose': {
      id: '/_authenticated/sender/compose'
      path: '/sender/compose'
      fullPath: '/sender/compose'
      preLoaderRoute: typeof AuthenticatedSenderComposeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/smtp': {
      id: '/_authenticated/admin/smtp'
      path: '/admin/smtp'
      fullPath: '/admin/smtp'
      preLoaderRoute: typeof AuthenticatedAdminSmtpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/senders': {
      id: '/_authenticated/admin/senders'
      path: '/admin/senders'
      fullPath: '/admin/senders'
      preLoaderRoute: typeof AuthenticatedAdminSendersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/csv': {
      id: '/_authenticated/admin/csv'
      path: '/admin/csv'
      fullPath: '/admin/csv'
      preLoaderRoute: typeof AuthenticatedAdminCsvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedAdminCsvRoute: typeof AuthenticatedAdminCsvRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminSendersRoute: typeof AuthenticatedAdminSendersRoute
  AuthenticatedAdminSmtpRoute: typeof AuthenticatedAdminSmtpRoute
  AuthenticatedSenderComposeRoute: typeof AuthenticatedSenderComposeRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedSenderIndexRoute: typeof AuthenticatedSenderIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedAdminCsvRoute: AuthenticatedAdminCsvRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminSendersRoute: AuthenticatedAdminSendersRoute,
  AuthenticatedAdminSmtpRoute: AuthenticatedAdminSmtpRoute,
  AuthenticatedSenderComposeRoute: AuthenticatedSenderComposeRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedSenderIndexRoute: AuthenticatedSenderIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
